<a href="https://colab.research.google.com/github/adtitovich/dsml-17/blob/main/m4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Описание задания:
В домашней работе необходимо провести очистку данных на примере датасета с информацией о пассажирах корабля Титаник. Данные можно скачать по [ссылке](https://www.kaggle.com/hesh97/titanicdataset-traincsv) или найти в материалах к уроку. 
На полученных данных обучите модель классификации, с целевым признаком Survived (1 – пассажир выжил, 0 – погиб). Обучите модель на необработанных данных и посчитайте метрику качества. 
Проведите очистку данных. Обучите модель на данных после обработки, посчитайте метрику качества. Сравнить полученные результаты. Значение метрики должно улучшиться.

#Этапы работы:
**Получите и загрузите данные.**

Data Dictionary

survival	Survival	0 = No, 1 = Yes
pclass	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd  
sex	Sex	
Age	Age in years	
sibsp	# of siblings / spouses aboard the Titanic	
parch	# of parents / children aboard the Titanic	
ticket	Ticket number	
fare	Passenger fare	
cabin	Cabin number	
embarked	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton

Variable Notes
pclass: A proxy for socio-economic status (SES)
1st = Upper
2nd = Middle
3rd = Lower
age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5  
sibsp: The dataset defines family relations in this way...  
Sibling = brother, sister, stepbrother, stepsister  
Spouse = husband, wife (mistresses and fiancés were ignored)  
parch: The dataset defines family relations in this way...  
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.

In [1]:
import pandas as pd

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/adtitovich/dsml-17/main/datasets/train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


**Удалите все пропущенные значения и категориальные переменные. Обучите модель. Выберете и посчитайте метрику качества.**

In [ ]:
# удаляем пропущенные значения и категориальные переменные
data = data.drop(columns=['PassengerId', 'Pclass', 'Name',  'Sex', 'Ticket', 'Cabin',  'Embarked'])
data = data.dropna()

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Age       714 non-null    float64
 2   SibSp     714 non-null    int64  
 3   Parch     714 non-null    int64  
 4   Fare      714 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 33.5 KB


In [ ]:
X = data[['Age', 'SibSp', 'Parch', 'Fare']]
y = data['Survived']

In [ ]:
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000))
model.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=2000))])

In [ ]:
# Recall
recall_score(y, model.predict(X))

0.33448275862068966

**Снова загрузите полные данные.
Удалите признаки, которые логически не нужны для построения модели. Обоснуйте.**

In [97]:
data = pd.read_csv('https://raw.githubusercontent.com/adtitovich/dsml-17/main/datasets/train.csv')

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    int64  
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     891 non-null    object 
 12  deck         204 non-null    object 
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


признаки, которые использовать не будем:    
PassengerId (это просто идентификатор)   
Name - по сути тот же идентификатор  
Ticket - номер билета, наличие нескольких покупателей в одном билете компенсируется признаками SibSp и Parch.    
Fare - тариф, зависит от класса Pclass и кол-ва людей в билете.   

Cabin - составное значение, состоящие из номера палубы и каюты.   
На палубах c A по E были расположены каюты первого класса, 
На палубах c D по G – второй и третий класс

Создадим новый категориальный признак - номер палубы (deck) 


In [98]:
data['deck'] = data['Cabin'].str[:1]

Пропуски в признаке 'Age' заменим на среднее значение

In [99]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

Проверим пропуски в признаке 'Embarked' заменим их на наиболее частый порт посадки пассажиров первого класса

In [100]:
data[data['Embarked'].isna()].head()


PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked deck  
61   female  38.0      0      0  113572  80.0   B28      NaN    B  
829  female  62.0      0      0  113572  80.0   B28      NaN    B

In [101]:
data['Embarked'] = data['Embarked'].fillna(data[data['Pclass'] == 1]['Embarked'].value_counts()[0])

Переведем признак 'Sex' в int (male = 1; female = 0)
 

In [102]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [103]:
data['Sex'] = data['Sex'].apply(lambda x: 1 if x =='male' else 0).astype('int')

Проверим данные на наличие выбросов по оставшимся признакам

In [104]:
data.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642    0.647587   29.699118   
std     257.353842    0.486592    0.836071    0.477990   13.002015   
min       1.000000    0.000000    1.000000    0.000000    0.420000   
25%     223.500000    0.000000    2.000000    0.000000   22.000000   
50%     446.000000    0.000000    3.000000    1.000000   29.699118   
75%     668.500000    1.000000    3.000000    1.000000   35.000000   
max     891.000000    1.000000    3.000000    1.000000   80.000000   

            SibSp       Parch        Fare  
count  891.000000  891.000000  891.000000  
mean     0.523008    0.381594   32.204208  
std      1.102743    0.806057   49.693429  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    7.910400  
50%      0.000000    0.000000   14.454200  
75%      1.000000    0.000000   31.000000  
max      8.000000    6.000000  512.329200

sibsp: brother, sister, stepbrother, stepsister  + husband, wife (mistresses and fiancés were ignored)     
parch: mother, father + daughter, son, stepdaughter, stepson   
Some children travelled only with a nanny, therefore parch=0 for them.

In [105]:
# посмотрим на SibSp=8
data[data['SibSp'] == 8].head(20)

PassengerId  Survived  Pclass                               Name  Sex  \
159          160         0       3         Sage, Master. Thomas Henry    1   
180          181         0       3       Sage, Miss. Constance Gladys    0   
201          202         0       3                Sage, Mr. Frederick    1   
324          325         0       3           Sage, Mr. George John Jr    1   
792          793         0       3            Sage, Miss. Stella Anna    0   
846          847         0       3           Sage, Mr. Douglas Bullen    1   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"    0   

           Age  SibSp  Parch    Ticket   Fare Cabin Embarked deck  
159  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
180  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
201  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
324  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
792  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
846  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
863  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN

In [106]:
data[data['Ticket'].str.contains('CA. 2343')]

PassengerId  Survived  Pclass                               Name  Sex  \
159          160         0       3         Sage, Master. Thomas Henry    1   
180          181         0       3       Sage, Miss. Constance Gladys    0   
201          202         0       3                Sage, Mr. Frederick    1   
324          325         0       3           Sage, Mr. George John Jr    1   
792          793         0       3            Sage, Miss. Stella Anna    0   
846          847         0       3           Sage, Mr. Douglas Bullen    1   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"    0   

           Age  SibSp  Parch    Ticket   Fare Cabin Embarked deck  
159  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
180  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
201  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
324  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
792  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
846  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN  
863  29.699118      8      2  CA. 2343  69.55   NaN        S  NaN

Похоже на то что это 7 братьев-сестер. Возраст не указан (у нас теперь среднее значение), родителей в каюте нет. Соответственно, для них SibSp = 6, Parch = 0

In [107]:
data.loc[data['SibSp'] == 8, 'Parch'] = 0
data.loc[data['SibSp'] == 8, 'SibSp'] = 6

In [108]:
# посмотрим на Parch=6
data[data['Parch'] == 6].head(20)

PassengerId  Survived  Pclass                                     Name  \
678          679         0       3  Goodwin, Mrs. Frederick (Augusta Tyler)   

     Sex   Age  SibSp  Parch   Ticket  Fare Cabin Embarked deck  
678    0  43.0      1      6  CA 2144  46.9   NaN        S  NaN

In [109]:
data[data['Ticket'].str.contains('CA 2144')]

PassengerId  Survived  Pclass                                     Name  \
59            60         0       3       Goodwin, Master. William Frederick   
71            72         0       3               Goodwin, Miss. Lillian Amy   
386          387         0       3          Goodwin, Master. Sidney Leonard   
480          481         0       3           Goodwin, Master. Harold Victor   
678          679         0       3  Goodwin, Mrs. Frederick (Augusta Tyler)   
683          684         0       3              Goodwin, Mr. Charles Edward   

     Sex   Age  SibSp  Parch   Ticket  Fare Cabin Embarked deck  
59     1  11.0      5      2  CA 2144  46.9   NaN        S  NaN  
71     0  16.0      5      2  CA 2144  46.9   NaN        S  NaN  
386    1   1.0      5      2  CA 2144  46.9   NaN        S  NaN  
480    1   9.0      5      2  CA 2144  46.9   NaN        S  NaN  
678    0  43.0      1      6  CA 2144  46.9   NaN        S  NaN  
683    1  14.0      5      2  CA 2144  46.9   NaN        S  NaN

In [110]:
data[data['Name'].str.contains('Goodwin')]  

PassengerId  Survived  Pclass                                     Name  \
59            60         0       3       Goodwin, Master. William Frederick   
71            72         0       3               Goodwin, Miss. Lillian Amy   
386          387         0       3          Goodwin, Master. Sidney Leonard   
480          481         0       3           Goodwin, Master. Harold Victor   
678          679         0       3  Goodwin, Mrs. Frederick (Augusta Tyler)   
683          684         0       3              Goodwin, Mr. Charles Edward   

     Sex   Age  SibSp  Parch   Ticket  Fare Cabin Embarked deck  
59     1  11.0      5      2  CA 2144  46.9   NaN        S  NaN  
71     0  16.0      5      2  CA 2144  46.9   NaN        S  NaN  
386    1   1.0      5      2  CA 2144  46.9   NaN        S  NaN  
480    1   9.0      5      2  CA 2144  46.9   NaN        S  NaN  
678    0  43.0      1      6  CA 2144  46.9   NaN        S  NaN  
683    1  14.0      5      2  CA 2144  46.9   NaN        S  NaN

Очень похоже на мать + 5 детей. Тогда для id=678 должно быть SibSp = 0, Parch = 5. Для остальных в билете 'CA 2144'  SibSp = 4, Parch = 1

In [111]:
data.loc[(data['Ticket'].str.contains('CA 2144')) & (data['SibSp'] == 5), 'Parch'] = 1
data.loc[(data['Ticket'].str.contains('CA 2144')) & (data['SibSp'] == 5), 'SibSp'] = 4

data.loc[678, 'SibSp'] = 0
data.loc[678, 'Parch'] = 5

Проверим признак 'Embarked' на аномалии

In [112]:
data['Embarked'].value_counts()

S      644
C      168
Q       77
127      2
Name: Embarked, dtype: int64

In [113]:
# значение 127 - аномалия
data[data['Embarked'] == 127]  

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

     Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked deck  
61     0  38.0      0      0  113572  80.0   B28      127    B  
829    0  62.0      0      0  113572  80.0   B28      127    B

In [114]:
# заменим их так же наиболее частый порт посадки пассажиров первого класса
data.loc[data['Embarked'] == 127, 'Embarked'] = 'S'



Проверим наш признак deck на аномалии

In [115]:
data['deck'].value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: deck, dtype: int64

In [116]:
# палуба T - это аномалия
data[data['deck'] == 'T']

PassengerId  Survived  Pclass                          Name  Sex   Age  \
339          340         0       1  Blackwell, Mr. Stephen Weart    1  45.0   

     SibSp  Parch  Ticket  Fare Cabin Embarked deck  
339      0      0  113784  35.5     T        S    T

In [117]:
data[data['Ticket'].str.contains('113784')]

PassengerId  Survived  Pclass                          Name  Sex   Age  \
339          340         0       1  Blackwell, Mr. Stephen Weart    1  45.0   

     SibSp  Parch  Ticket  Fare Cabin Embarked deck  
339      0      0  113784  35.5     T        S    T

In [118]:
# Заменим его на самую частую палубу для первого класса 'C'
data.loc[339, 'deck'] = 'C'

In [119]:
# удалим признаки, которые не будем использовать
data = data.drop(columns=['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin'])

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Embarked  891 non-null    object 
 7   deck      204 non-null    object 
dtypes: float64(1), int64(5), object(2)
memory usage: 55.8+ KB


Переведем Embarked в цифровое значение 

In [121]:
X = pd.get_dummies(data, columns = ['Embarked'])

Переведем deck в цифровое значение, добавляя стобец-индикатор, что значение было пропущено

In [123]:
X = pd.get_dummies(X, columns = ['deck' ], dummy_na=True)

In [124]:
X.head(20)

Survived  Pclass  Sex        Age  SibSp  Parch  Embarked_C  Embarked_Q  \
0          0       3    1  22.000000      1      0           0           0   
1          1       1    0  38.000000      1      0           1           0   
2          1       3    0  26.000000      0      0           0           0   
3          1       1    0  35.000000      1      0           0           0   
4          0       3    1  35.000000      0      0           0           0   
5          0       3    1  29.699118      0      0           0           1   
6          0       1    1  54.000000      0      0           0           0   
7          0       3    1   2.000000      3      1           0           0   
8          1       3    0  27.000000      0      2           0           0   
9          1       2    0  14.000000      1      0           1           0   
10         1       3    0   4.000000      1      1           0           0   
11         1       1    0  58.000000      0      0           0           0   
12         0       3    1  20.000000      0      0           0           0   
13         0       3    1  39.000000      1      5           0           0   
14         0       3    0  14.000000      0      0           0           0   
15         1       2    0  55.000000      0      0           0           0   
16         0       3    1   2.000000      4      1           0           1   
17         1       2    1  29.699118      0      0           0           0   
18         0       3    0  31.000000      1      0           0           0   
19         1       3    0  29.699118      0      0           1           0   

    Embarked_S  deck_A  deck_B  deck_C  deck_D  deck_E  deck_F  deck_G  \
0            1       0       0       0       0       0       0       0   
1            0       0       0       1       0       0       0       0   
2            1       0       0       0       0       0       0       0   
3            1       0       0       1       0       0       0       0   
4            1       0       0       0       0       0       0       0   
5            0       0       0       0       0       0       0       0   
6            1       0       0       0       0       1       0       0   
7            1       0       0       0       0       0       0       0   
8            1       0       0       0       0       0       0       0   
9            0       0       0       0       0       0       0       0   
10           1       0       0       0       0       0       0       1   
11           1       0       0       1       0       0       0       0   
12           1       0       0       0       0       0       0       0   
13           1       0       0       0       0       0       0       0   
14           1       0       0       0       0       0       0       0   
15           1       0       0       0       0       0       0       0   
16           0       0       0       0       0       0       0       0   
17           1       0       0       0       0       0       0       0   
18           1       0       0       0       0       0       0       0   
19           0       0       0       0       0       0       0       0   

    deck_nan  
0          1  
1          0  
2          1  
3          0  
4          1  
5          1  
6          0  
7          1  
8          1  
9          1  
10         0  
11         0  
12         1  
13         1  
14         1  
15         1  
16         1  
17         1  
18         1  
19         1

In [126]:
# заносим в таргетную переменную Survived
y = data['Survived']
del X['Survived']

In [128]:
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000))
model.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=2000))])

In [129]:
# Recall
recall_score(y, model.predict(X))

0.7339181286549707